### ISSUE TITLE
Can I predetermine the winner?

### ISSUE THREAD

**Issue by shayanafkane** [icelam/random-name-picker#2]

**Comment by icelam** [comment]
Unfortunately, this is not the purpose of this app. This app aims to provide a "fair" winner picking mechanism by shuffling a list of names input by user.

If you want the ability to predefine / predetermine the winner, welcome to fork this repo and apply your own customization. The code is located here:

https://github.com/icelam/random-name-picker/blob/49e1e8fa9ae2b468aab1719d852cc57ad3a745f4/src/assets/js/Slot.ts#L174-L200
